/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLibrariesIndexRouteImport } from './routes/_authenticated.libraries.index'
import { Route as AuthenticatedLibrariesLibraryIdRouteImport } from './routes/_authenticated.libraries.$libraryId'
import { Route as AuthenticatedLibrariesLibraryIdIndexRouteImport } from './routes/_authenticated.libraries.$libraryId.index'
import { Route as AuthenticatedLibrariesLibraryIdVideosRouteImport } from './routes/_authenticated.libraries.$libraryId.videos'
import { Route as AuthenticatedLibrariesLibraryIdSettingsRouteImport } from './routes/_authenticated.libraries.$libraryId.settings'
import { Route as AuthenticatedLibrariesLibraryIdVideosIndexRouteImport } from './routes/_authenticated.libraries.$libraryId.videos.index'
import { Route as AuthenticatedLibrariesLibraryIdVideosVideoIdRouteImport } from './routes/_authenticated.libraries.$libraryId.videos.$videoId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLibrariesIndexRoute =
  AuthenticatedLibrariesIndexRouteImport.update({
    id: '/libraries/',
    path: '/libraries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.libraries.index.lazy').then((d) => d.Route),
  )
const AuthenticatedLibrariesLibraryIdRoute =
  AuthenticatedLibrariesLibraryIdRouteImport.update({
    id: '/libraries/$libraryId',
    path: '/libraries/$libraryId',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.libraries.$libraryId.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedLibrariesLibraryIdIndexRoute =
  AuthenticatedLibrariesLibraryIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.libraries.$libraryId.index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedLibrariesLibraryIdVideosRoute =
  AuthenticatedLibrariesLibraryIdVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdRoute,
  } as any)
const AuthenticatedLibrariesLibraryIdSettingsRoute =
  AuthenticatedLibrariesLibraryIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.libraries.$libraryId.settings.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedLibrariesLibraryIdVideosIndexRoute =
  AuthenticatedLibrariesLibraryIdVideosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdVideosRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.libraries.$libraryId.videos.index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedLibrariesLibraryIdVideosVideoIdRoute =
  AuthenticatedLibrariesLibraryIdVideosVideoIdRouteImport.update({
    id: '/$videoId',
    path: '/$videoId',
    getParentRoute: () => AuthenticatedLibrariesLibraryIdVideosRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.libraries.$libraryId.videos.$videoId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/libraries/$libraryId': typeof AuthenticatedLibrariesLibraryIdRouteWithChildren
  '/libraries/': typeof AuthenticatedLibrariesIndexRoute
  '/libraries/$libraryId/settings': typeof AuthenticatedLibrariesLibraryIdSettingsRoute
  '/libraries/$libraryId/videos': typeof AuthenticatedLibrariesLibraryIdVideosRouteWithChildren
  '/libraries/$libraryId/': typeof AuthenticatedLibrariesLibraryIdIndexRoute
  '/libraries/$libraryId/videos/$videoId': typeof AuthenticatedLibrariesLibraryIdVideosVideoIdRoute
  '/libraries/$libraryId/videos/': typeof AuthenticatedLibrariesLibraryIdVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/libraries': typeof AuthenticatedLibrariesIndexRoute
  '/libraries/$libraryId/settings': typeof AuthenticatedLibrariesLibraryIdSettingsRoute
  '/libraries/$libraryId': typeof AuthenticatedLibrariesLibraryIdIndexRoute
  '/libraries/$libraryId/videos/$videoId': typeof AuthenticatedLibrariesLibraryIdVideosVideoIdRoute
  '/libraries/$libraryId/videos': typeof AuthenticatedLibrariesLibraryIdVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/libraries/$libraryId': typeof AuthenticatedLibrariesLibraryIdRouteWithChildren
  '/_authenticated/libraries/': typeof AuthenticatedLibrariesIndexRoute
  '/_authenticated/libraries/$libraryId/settings': typeof AuthenticatedLibrariesLibraryIdSettingsRoute
  '/_authenticated/libraries/$libraryId/videos': typeof AuthenticatedLibrariesLibraryIdVideosRouteWithChildren
  '/_authenticated/libraries/$libraryId/': typeof AuthenticatedLibrariesLibraryIdIndexRoute
  '/_authenticated/libraries/$libraryId/videos/$videoId': typeof AuthenticatedLibrariesLibraryIdVideosVideoIdRoute
  '/_authenticated/libraries/$libraryId/videos/': typeof AuthenticatedLibrariesLibraryIdVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/libraries/$libraryId'
    | '/libraries/'
    | '/libraries/$libraryId/settings'
    | '/libraries/$libraryId/videos'
    | '/libraries/$libraryId/'
    | '/libraries/$libraryId/videos/$videoId'
    | '/libraries/$libraryId/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/libraries'
    | '/libraries/$libraryId/settings'
    | '/libraries/$libraryId'
    | '/libraries/$libraryId/videos/$videoId'
    | '/libraries/$libraryId/videos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/libraries/$libraryId'
    | '/_authenticated/libraries/'
    | '/_authenticated/libraries/$libraryId/settings'
    | '/_authenticated/libraries/$libraryId/videos'
    | '/_authenticated/libraries/$libraryId/'
    | '/_authenticated/libraries/$libraryId/videos/$videoId'
    | '/_authenticated/libraries/$libraryId/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/libraries/': {
      id: '/_authenticated/libraries/'
      path: '/libraries'
      fullPath: '/libraries/'
      preLoaderRoute: typeof AuthenticatedLibrariesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/libraries/$libraryId': {
      id: '/_authenticated/libraries/$libraryId'
      path: '/libraries/$libraryId'
      fullPath: '/libraries/$libraryId'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/libraries/$libraryId/': {
      id: '/_authenticated/libraries/$libraryId/'
      path: '/'
      fullPath: '/libraries/$libraryId/'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdIndexRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdRoute
    }
    '/_authenticated/libraries/$libraryId/videos': {
      id: '/_authenticated/libraries/$libraryId/videos'
      path: '/videos'
      fullPath: '/libraries/$libraryId/videos'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdVideosRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdRoute
    }
    '/_authenticated/libraries/$libraryId/settings': {
      id: '/_authenticated/libraries/$libraryId/settings'
      path: '/settings'
      fullPath: '/libraries/$libraryId/settings'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdSettingsRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdRoute
    }
    '/_authenticated/libraries/$libraryId/videos/': {
      id: '/_authenticated/libraries/$libraryId/videos/'
      path: '/'
      fullPath: '/libraries/$libraryId/videos/'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdVideosIndexRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdVideosRoute
    }
    '/_authenticated/libraries/$libraryId/videos/$videoId': {
      id: '/_authenticated/libraries/$libraryId/videos/$videoId'
      path: '/$videoId'
      fullPath: '/libraries/$libraryId/videos/$videoId'
      preLoaderRoute: typeof AuthenticatedLibrariesLibraryIdVideosVideoIdRouteImport
      parentRoute: typeof AuthenticatedLibrariesLibraryIdVideosRoute
    }
  }
}

interface AuthenticatedLibrariesLibraryIdVideosRouteChildren {
  AuthenticatedLibrariesLibraryIdVideosVideoIdRoute: typeof AuthenticatedLibrariesLibraryIdVideosVideoIdRoute
  AuthenticatedLibrariesLibraryIdVideosIndexRoute: typeof AuthenticatedLibrariesLibraryIdVideosIndexRoute
}

const AuthenticatedLibrariesLibraryIdVideosRouteChildren: AuthenticatedLibrariesLibraryIdVideosRouteChildren =
  {
    AuthenticatedLibrariesLibraryIdVideosVideoIdRoute:
      AuthenticatedLibrariesLibraryIdVideosVideoIdRoute,
    AuthenticatedLibrariesLibraryIdVideosIndexRoute:
      AuthenticatedLibrariesLibraryIdVideosIndexRoute,
  }

const AuthenticatedLibrariesLibraryIdVideosRouteWithChildren =
  AuthenticatedLibrariesLibraryIdVideosRoute._addFileChildren(
    AuthenticatedLibrariesLibraryIdVideosRouteChildren,
  )

interface AuthenticatedLibrariesLibraryIdRouteChildren {
  AuthenticatedLibrariesLibraryIdSettingsRoute: typeof AuthenticatedLibrariesLibraryIdSettingsRoute
  AuthenticatedLibrariesLibraryIdVideosRoute: typeof AuthenticatedLibrariesLibraryIdVideosRouteWithChildren
  AuthenticatedLibrariesLibraryIdIndexRoute: typeof AuthenticatedLibrariesLibraryIdIndexRoute
}

const AuthenticatedLibrariesLibraryIdRouteChildren: AuthenticatedLibrariesLibraryIdRouteChildren =
  {
    AuthenticatedLibrariesLibraryIdSettingsRoute:
      AuthenticatedLibrariesLibraryIdSettingsRoute,
    AuthenticatedLibrariesLibraryIdVideosRoute:
      AuthenticatedLibrariesLibraryIdVideosRouteWithChildren,
    AuthenticatedLibrariesLibraryIdIndexRoute:
      AuthenticatedLibrariesLibraryIdIndexRoute,
  }

const AuthenticatedLibrariesLibraryIdRouteWithChildren =
  AuthenticatedLibrariesLibraryIdRoute._addFileChildren(
    AuthenticatedLibrariesLibraryIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedLibrariesLibraryIdRoute: typeof AuthenticatedLibrariesLibraryIdRouteWithChildren
  AuthenticatedLibrariesIndexRoute: typeof AuthenticatedLibrariesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLibrariesLibraryIdRoute:
    AuthenticatedLibrariesLibraryIdRouteWithChildren,
  AuthenticatedLibrariesIndexRoute: AuthenticatedLibrariesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
